version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "PatientDBFunctions.yaml"
        "S3_BUCKET": "codepipeline-us-east-2-246529850718"
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - pushd app
                    - ls app
                    - npm install 
                    - popd
                    - pushd authorizer
                    - npm install
                    - popd
                    - aws cloudformation package --template patientdbAPI.yaml --s3-bucket codepipeline-us-east-2-246529850718 --output-template post-saml.yaml
        artifacts:
            files:
                - post-saml.yaml
                - app/node_modules/*
                - authorizer/node_modules/*
                - app/assets/*
