version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "PatientDBFunctions.yaml"
        "S3_BUCKET": "codepipeline-us-east-2-246529850718"
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - cd app
                    - npm install app --prefix ./app
                    - cd authorizer
                    - npm install authorizer --prefix ./authorizer
                    - cd ..
                    - aws cloudformation package --template patientdbAPI.yaml --s3-bucket codepipeline-us-east-2-246529850718 --output-template post-saml-us-east-2.yaml
                    - aws cloudformation package --template patientdbAPI.yaml --s3-bucket codepipeline-ap-south-1-224059767813 --output-template post-saml-ap-south-1.yaml
        artifacts:
            files:
                - post-saml-us-east-2.yaml
                - post-saml-ap-south-1.yaml
                - 'app/*'
                - 'authorizer/*'
